sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  redis:
        host: localhost
        port: 6379
        password: 123456
        database: 10
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALIYUN_OSS_ACCESS_KEY_ID:你的AccessKeyId}
    access-key-secret: ${ALIYUN_OSS_ACCESS_KEY_SECRET:你的AccessKeySecret}
    bucket-name: lhz-sky-takeout
  wechat:
    appid: wx370244f29690e07e
    secret: fcba8dca17525cff1702b0e7614bfc0f